server:
  port: ${PORT:8086} # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:http://localhost:8086} # Valor por defecto si SERVER_URL no está configurado

spring:
  application:
    name: AIOME
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-lucky-band-acmf0c65-pooler.sa-east-1.aws.neon.tech:5432/apis?sslmode=require&channel_binding=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_5hATvbrqKD9o}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    copilot:
      api-key: ${COPILOT_API_KEY:70d2b19518msh27c0dc634d2bfd1p1dea1djsncacae4126f0f}
      api-host: ${COPILOT_API_HOST:copilot11.p.rapidapi.com}
      api-url: ${COPILOT_API_URL:https://copilot11.p.rapidapi.com/}
    gemini:
      api-key: ${GEMINI_API_KEY:AIzaSyAWvrzXRCrTrP5LVQB4cDd5_ACvkqRh_vw}
      api-url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:*}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}

logging:
  level:
    org.springframework.web: DEBUG
    org.springdoc: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false
  packages-to-scan: edu.pe.vallegrande.AIOME.controller